B14 API Delete Laptop (Delete)
aldhisttd/2023_5pagia_laptop_be pull request #11
Opened 2023-12-30 06:19 UTC by yesayas17

![image](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/87988af8-7666-4a8a-b5b9-dd70fae41a46)
![image](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/ce3bb1ec-a541-4314-aa6d-06a4af00fb13)
![image](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/5c8dae15-1599-484d-8123-21e6dc4a2813)
![image](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/ec64f621-711e-4d1f-850e-c2a26378bb4b)

sudah menghilangkan upload/  dan menghapus semua file gambar di upload
@aldhi88 @aldhisttd

2023-12-31 05:08 UTC, aldhi88 requested changes

2023-12-31 05:08 UTC, aldhi88 commented on laptop_delete.php
> +$kode = mysqli_real_escape_string($koneksi, $_REQUEST['kode']);
@yesayas17 ngambil kode dari payload gak seperti ini, ambil biasa aja

2023-12-31 05:08 UTC, aldhi88 commented on laptop_delete.php
> +    if (isset($dt['gambar']) && !empty($dt['gambar'])) {
@yesayas17 gakusah ada validasi lagi, langsung hapus aja

2023-12-31 15:51 UTC, yesayas17 commented on laptop_delete.php
> +$kode = mysqli_real_escape_string($koneksi, $_REQUEST['kode']);
@aldhi88 baik pak, sudah saya perbaiki

2023-12-31 15:51 UTC, yesayas17 commented on laptop_delete.php
> +    if (isset($dt['gambar']) && !empty($dt['gambar'])) {
@aldhi88 baik pak, tanpa validasi

2023-12-31 15:54 UTC, yesayas17 commented
pak @aldhi88 saya sudah memperbaiki kesalahan diantaranya mengambil kode payload seperti biasanya dan tanpa validasi

2023-12-31 22:54 UTC, aldhi88 requested changes

2023-12-31 22:54 UTC, aldhi88 commented on laptop_delete.php
> +    {
@yesayas17 lah ini mksdnya gmn sih code kamu

2024-01-01 06:48 UTC, yesayas17 commented on laptop_delete.php
> +    {
sudah saya perbaiki pak, semoga jadi done pak

2024-01-02 06:54 UTC, aldhi88 requested changes

2024-01-02 06:54 UTC, aldhi88 commented on laptop_delete.php
> +    $res['body']['data']['kode'] = "$kode";
@yesayas17 ini hapus tanda " di `$kode`

2024-01-02 06:54 UTC, aldhi88 commented on laptop_delete.php
> +    $res['body']['data']['kode'] = "$kode";
@yesayas17 ini hapus tanda " di `$kode`

2024-01-02 09:06 UTC, yesayas17 commented on laptop_delete.php
> +    $res['body']['data']['kode'] = "$kode";
sudah saya hapus pak

2024-01-02 09:06 UTC, yesayas17 commented on laptop_delete.php
> +    $res['body']['data']['kode'] = "$kode";
saya sudah menghapusnya pak, dan sudah saya lakukan pull master sebelum pr

2024-01-03 01:27 UTC, aldhi88 approved these changes

2024-01-03 01:27 UTC, merged