B14 API Delete Laptop (Delete)
aldhisttd/2023_5pagia_laptop_be pull request #6
Opened 2023-12-26 14:36 UTC by yesayas17

database sebelum API
![WhatsApp Image 2023-12-26 at 21 09 29_80513178](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/3d2db990-62f0-4ebf-b9dd-b8ac2c98cbec)

API dengan gambar (sebelum)
![WhatsApp Image 2023-12-26 at 21 11 11_2eda0ec9](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/4daded72-e15e-43bc-888a-6f79ea7d3a91)

API dengan gambar (setelah)
![WhatsApp Image 2023-12-26 at 21 11 55_ba5cdb97](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/eda0772b-00b4-4649-a0e7-d851f0904d71)

database setelah API
![WhatsApp Image 2023-12-26 at 21 12 15_0cc604ad](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/6b17b289-b470-40fc-8b6f-0e1344f1d890)

izin pak, apakah ini sudah benar?
@aldhi88 
@aldhisttd

2023-12-27 04:07 UTC, aldhi88 requested changes
@yesayas17 sebelum push PR, harusnya pull master dulu, lokasi gambar harusnya ada di folder upload, silahkan pull master dulu

2023-12-28 06:07 UTC, yesayas17 commented
![WhatsApp Image 2023-12-27 at 14 29 06_0997889a](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/108356951/057d065c-c29c-4430-87e3-973fcbad4b70)
izin pak, mengubah lokasi gambar di upload dan sudah  di pull terlebih dahulu.
@aldhi88 
@aldhisttd

2023-12-29 03:53 UTC, aldhi88 requested changes
@yesayas17 perbaiki

2023-12-29 03:53 UTC, aldhi88 commented on upload/.gitignore
@yesayas17 ini kenapa kamu hapus ,

2023-12-29 03:53 UTC, aldhi88 commented on laptop_read.php
@yesayas17 ini juga kenapa di hapus

2023-12-29 16:05 UTC, yesayas17 commented on laptop_read.php
sudah saya perbaiki pak dan sudah saya pull master terlebih dahulu pak, mohon dicek pak @aldhi88 @aldhisttd

2023-12-30 00:32 UTC, aldhi88 requested changes
@yesayas17 

- dari branch kamu, lakukan `git pull origin master`, 
- hapus semua file gambar di folder upload

2023-12-30 00:32 UTC, aldhi88 commented on laptop_delete.php
> +        unlink('upload/' . $gambar);
@yesayas17 ini gak usah ada `upload/` nya lagi

2023-12-30 06:07 UTC, closed without merging