B15-API-Update-Laptop-Update
aldhisttd/2023_5pagia_laptop_be pull request #7
Opened 2023-12-26 17:17 UTC by agungsyhptra

![Screenshot (138)](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/129131946/233f4095-8b0a-4f22-a9a3-84945136b5ab)
![Screenshot (140)](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/129131946/98e568ef-16e3-494c-9e51-17132c2de3e2)
![Screenshot (139)](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/129131946/92d7e09d-4ed3-4aa1-8e00-4fcf71d79d54)
@aldhi88

2023-12-27 04:00 UTC, aldhi88 requested changes
@agungsyhptra pull master dulu sebelum push PR

2023-12-28 10:47 UTC, agungsyhptra commented
sudah pak @aldhi88

2023-12-29 04:19 UTC, aldhi88 requested changes

2023-12-29 04:19 UTC, aldhi88 commented on upload/d4282c932c4ab48d70a520af57a45a1a.png
@agungsyhptra ini kenapa di push

2023-12-29 04:19 UTC, aldhi88 commented on laptop_update.php
> +    $namaGambarBaru = 'gambar.jpg';
@agungsyhptra ini untuk apa?

2023-12-29 04:19 UTC, aldhi88 commented on laptop_update.php
> +    http_response_code(400);
@agungsyhptra ini siapa yg ngajarin ya

2023-12-29 04:19 UTC, aldhi88 commented on laptop_update.php
> +    $response = array(
@agungsyhptra pastikan response nya sesuai api spec

2024-01-03 01:31 UTC, aldhi88 requested changes
@agungsyhptra , flow nya:

- cek data exist di DB or not, jika ada lanjut di bawah, jika tidak response 400
- hapus gambar lama
- update data di DB jika berhasil lanjut bawah,
- upload gambar baru

2024-01-04 14:28 UTC, aldhi88 requested changes

2024-01-04 14:28 UTC, aldhi88 commented on laptop_update.php
> +            unlink("upload/" . $gambar);
@agungsyhptra gak perlu ada `upload/` nya, di DB nnti urlnya sudah include `upload/nama_gambar`

2024-01-04 14:29 UTC, aldhi88 requested changes

2024-01-04 14:29 UTC, aldhi88 commented on laptop_update.php
> +                            SET kode = '$kode',
@agungsyhptra kode kok di edit sih

2024-01-04 14:47 UTC, aldhi88 approved these changes

2024-01-04 14:47 UTC, merged