B13 API Data By ID Laptop (Read By ID)
aldhisttd/2023_5pagia_laptop_be pull request #8
Opened 2023-12-28 15:51 UTC by srningsih

![WhatsApp Image 2023-12-28 at 22 16 32_73e7df47](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/129132343/5cc54bee-e8b1-4203-bff9-6f26db317624)
![WhatsApp Image 2023-12-28 at 22 24 29_d75fde19](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/129132343/b0e883cc-2f59-411d-901b-f2c658e1bc87)
![WhatsApp Image 2023-12-28 at 22 24 50_c239eb5a](https://github.com/aldhisttd/2023_5pagia_laptop_be/assets/129132343/61b986de-a717-43ea-bb0f-bfaf5f33b247)

API data by ID laptop 
@aldhi88 @aldhisttd

2023-12-29 04:07 UTC, aldhi88 requested changes

2023-12-29 04:07 UTC, aldhi88 commented on laptop_read_one.php
> +    $kode = mysqli_real_escape_string($koneksi, $_REQUEST['kode']);
@srningsih `$_REQUEST['kode']` --> ganti gini aja, jgn pake real_escape

2023-12-29 04:07 UTC, aldhi88 commented on laptop_read_one.php
> +    if ($result) {
@srningsih else nya mana

2024-01-03 01:44 UTC, aldhi88 requested changes

2024-01-03 01:44 UTC, aldhi88 commented on laptop_read_one.php
> +if (isset($_REQUEST['kode'])) {
@srningsih gak usah ada validasi cek klo handle `else` nya gak kamu buat

2024-01-03 02:17 UTC, srningsih commented on laptop_read_one.php
> +if (isset($_REQUEST['kode'])) {
Baik pak saya sudah perbaiki codingan nya

2024-01-03 03:10 UTC, aldhi88 approved these changes

2024-01-03 03:10 UTC, merged